package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseMerchantCust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantCust extends BaseMerchantCust<MerchantCust> {
	public static final MerchantCust dao = new MerchantCust().dao();
}
