package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseMerchantInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantInfo extends BaseMerchantInfo<MerchantInfo> {
	public static final MerchantInfo dao = new MerchantInfo().dao();
}
