package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseMerchantFeeAmountRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchantFeeAmountRecord extends BaseMerchantFeeAmountRecord<MerchantFeeAmountRecord> {
	public static final MerchantFeeAmountRecord dao = new MerchantFeeAmountRecord().dao();
}
