#namespace("collection_clear")
  #include("collection_clear.sql")
#end
#namespace("collection_entrust")
  #include("collection_entrust.sql")
#end
#namespace("merchant")
  #include("merchant.sql")
#end
#namespace("collection_trade")
  #include("collection_trade.sql")
#end