package com.mybank.pc.core;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.mybank.pc.admin.model.*;
import com.mybank.pc.collection.model.CollectionClear;
import com.mybank.pc.collection.model.CollectionEntrust;
import com.mybank.pc.collection.model.CollectionTrade;
import com.mybank.pc.collection.model.UnionpayEntrust;
import com.mybank.pc.merchant.model.MerchantCust;
import com.mybank.pc.merchant.model.MerchantFee;
import com.mybank.pc.merchant.model.MerchantInfo;
import com.mybank.pc.merchant.model.MerchantUser;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("s_param", Param.class);
		arp.addMapping("s_res", Res.class);
		arp.addMapping("s_role", Role.class);
		arp.addMapping("s_role_res", RoleRes.class);
		arp.addMapping("s_user", User.class);
		arp.addMapping("s_user_role", UserRole.class);
		arp.addMapping("s_content", Content.class);
		arp.addMapping("s_mapping", Mapping.class);
		arp.addMapping("s_taxonomy", Taxonomy.class);
		arp.addMapping("s_attachment", Attachment.class);
		arp.addMapping("merchant_info", MerchantInfo.class);
		arp.addMapping("merchant_fee", MerchantFee.class);
		arp.addMapping("merchant_cust", MerchantCust.class);
		arp.addMapping("merchant_user", MerchantUser.class);
		arp.addMapping("collection_clear", CollectionClear.class);
		arp.addMapping("collection_cleartotle", com.mybank.pc.collection.model.CollectionCleartotle.class);
		arp.addMapping("collection_trade", CollectionTrade.class);
		arp.addMapping("s_ufile", Ufile.class);
		arp.addMapping("collection_entrust", CollectionEntrust.class);
		arp.addMapping("unionpay_entrust", UnionpayEntrust.class);
		arp.addMapping("log_op", LogOp.class);
	}
}
