package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseCollectionCleartotle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionCleartotle extends BaseCollectionCleartotle<CollectionCleartotle> {
	public static final CollectionCleartotle dao = new CollectionCleartotle().dao();
}
