package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseCollectionEntrust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionEntrust extends BaseCollectionEntrust<CollectionEntrust> {
	public static final CollectionEntrust dao = new CollectionEntrust().dao();

	public CollectionEntrust findOne() {
		CollectionEntrust result = null;
		try {
			result = dao.findFirst(
					"SELECT * FROM collection_entrust WHERE customerNm = ? AND certifId = ? AND accNo = ? AND merId = ?",
					getCustomerNm(), getCertifId(), getAccNo(), getMerId());
		} catch (Exception e) {
			e.printStackTrace();
			result = null;
		}
		return result;
	}
}
