package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseCollectionClear;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionClear extends BaseCollectionClear<CollectionClear> {
	public static final CollectionClear dao = new CollectionClear().dao();
}
