package com.mybank.pc.collection.model;

import com.mybank.pc.Consts;
import com.mybank.pc.collection.model.base.BaseCollectionClear;
import com.mybank.pc.kits.DateKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionClear extends BaseCollectionClear<CollectionClear> {
	public static final CollectionClear dao = new CollectionClear().dao();


	public String getMerName(){
		return getStr("merName");
	}

	public String getProfit(){
		return getBigDecimal("profit")==null?"0":getBigDecimal("profit").toString();
	}

	public String getClearTimeTxt(){
		return DateKit.dateToStr(getClearTime(),DateKit.yyyy_MM_dd);
	}

	@Override
	public String getTableName() {
		return "collection_clear";
	}

	public String getChargeAtTxt(){
		return getChargeAt()==null?Consts.BLANK:DateKit.dateToStr(getChargeAt(),DateKit.format4Login);
	}
}
