package com.mybank.pc.collection.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.SqlPara;
import com.mybank.pc.collection.model.base.BaseCollectionTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionTrade extends BaseCollectionTrade<CollectionTrade> {
	public static final CollectionTrade dao = new CollectionTrade().dao();

	public static CollectionTrade findByTradeNo(UnionpayCollection unionpayCollection) {
		SqlPara sqlPara = Db.getSqlPara("collection_trade.findByTradeNo", unionpayCollection);
		return dao.findFirst(sqlPara);
	}
}
