package com.mybank.pc.merchant.model;

import com.mybank.pc.merchant.model.base.BaseCollectionTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CollectionTrade extends BaseCollectionTrade<CollectionTrade> {
	public static final CollectionTrade dao = new CollectionTrade().dao();
}
