package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseUnionpayEntrust;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnionpayEntrust extends BaseUnionpayEntrust<UnionpayEntrust> {
	public static final UnionpayEntrust dao = new UnionpayEntrust().dao();
}
