package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseUnionpayBatchCollectionQuery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnionpayBatchCollectionQuery extends BaseUnionpayBatchCollectionQuery<UnionpayBatchCollectionQuery> {
	public static final UnionpayBatchCollectionQuery dao = new UnionpayBatchCollectionQuery().dao();
}
