package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseUnionpayCallbackLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnionpayCallbackLog extends BaseUnionpayCallbackLog<UnionpayCallbackLog> {
	public static final UnionpayCallbackLog dao = new UnionpayCallbackLog().dao();
}
