package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseUnionpayCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnionpayCollection extends BaseUnionpayCollection<UnionpayCollection> {
	public static final UnionpayCollection dao = new UnionpayCollection().dao();
}
