package com.mybank.pc.collection.model;

import com.mybank.pc.collection.model.base.BaseUnionpayBatchCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UnionpayBatchCollection extends BaseUnionpayBatchCollection<UnionpayBatchCollection> {
	public static final UnionpayBatchCollection dao = new UnionpayBatchCollection().dao();
}
